asdad

diff --git a/.github/workflows /update-version.yml b/.github/workflows /update-version.yml
--- a/.github/workflows /update-version.yml
+++ b/.github/workflows /update-version.yml
@@ -3,7 +3,7 @@ name: Increment Version
 on:
   push:
     branches:
-      - main
+      - master
 
 jobs:
   update-version:
@@ -12,6 +12,15 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+
+      - name: Ensure jq is available
+        run: |
+          if ! command -v jq &> /dev/null; then
+            echo "jq could not be found, installing..."
+            sudo apt-get update && sudo apt-get install -y jq
+          else
+            echo "jq is already installed"
+          fi
 
       - name: Increment version number
         id: increment_version
@@ -30,4 +39,3 @@ jobs:
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          
