Hello

diff --git a/.github/workflows /update-version.yml b/.github/workflows /update-version.yml
--- a/.github/workflows /update-version.yml
+++ b/.github/workflows /update-version.yml
@@ -2,44 +2,75 @@ name: Update Version
 
 on:
   push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+    branches: [ main ]
 
 jobs:
   update-version:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
 
-    - name: Set new version of app
-      id: set_version
-      env:
-         CURRENT_VERSION: ${{ secrets.APP_VERSION }}
+    - name: Fetch all branches
       run: |
-         echo "Current version from secret: $CURRENT_VERSION"
-         NEW_VERSION=$((CURRENT_VERSION + 1))
-         echo "New version: $NEW_VERSION"
-         echo "{\"version\": $NEW_VERSION}" > version.json
-         echo "CURRENT_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
+
+    - name: Set GitHub Actions user
+      run: |
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        git config user.name "GitHub Actions"
+
+    - name: Set up Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '16'
+        cache: 'npm'
+        cache-dependency-path: script/sync-ghes/package-lock.json
+
+    - name: Install dependencies
+      run: npm ci
+      working-directory: ./script/sync-ghes
+
+    - name: Increment version in JSON file
+      id: increment_version
+      run: |
+        VERSION_FILE=version.json
+        if [ ! -f "$VERSION_FILE" ]; then
+          echo "$VERSION_FILE does not exist"
+          exit 1
+        fi
+
+        echo "Current version file content:"
+        cat $VERSION_FILE
+
+        VERSION=$(jq .version $VERSION_FILE)
+
+        if [ -z "$VERSION" ]; then
+          echo "Failed to retrieve version from $VERSION_FILE"
+          exit 1
+        fi
+
+        echo "Current version is $VERSION"
+        
+        NEW_VERSION=$((VERSION + 1))
+
+        echo "New version is $NEW_VERSION"
+        
+        jq --arg new_version "$NEW_VERSION" '.version=($new_version | tonumber)' $VERSION_FILE > temp.json && mv temp.json $VERSION_FILE
+
+        echo "Updated version file content:"
+        cat $VERSION_FILE
 
     - name: Commit and push changes
       run: |
-        git config --global user.name 'github-actions[bot]'
-        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git add version.json
-        git commit -m "Increment version to ${{ env.CURRENT_VERSION }}"
-        git push
+        if [ -z "$(git status --porcelain)" ]; then
+          echo "No changes to commit"
+        else
+          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
+          git push
       env:
         MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-
-    - name: Update GitHub repo secret for future app builds
-      uses: hmanzur/actions-set-secret@v2.0.0
-      with:
-        name: 'APP_VERSION'
-        value: ${{ env.CURRENT_VERSION }}
-        token: ${{ secrets.MY_GITHUB_TOKEN }}
